version: "3.9"

services:
  go-api:
    build:
      context: .
      dockerfile: go-api/Dockerfile
    container_name: go-api
    ports:
      - "8080:8080"
    restart: unless-stopped

  cpp-worker:
    build:
      context: ./cpp-worker
      dockerfile: Dockerfile
    container_name: cpp-worker
    ports:
      - "3000:3000"
    restart: unless-stopped